project:
  type: book


filters:
  - acronyms
  - pseudocode

metadata-files:
  - _common.yml

book:
  title: "Missingness-Aware Learning for Downstream Tasks in Tabular and Time-series Data"
  author: "Rahul Bordoloi"
  date: "4/10/2026"
  chapters:
    - index.qmd
    # - mathCommands.qmd
    - preface/abstract.qmd
    - preface/zusammenfassung.qmd
    - preface/theses.qmd
    - preface/loa.qmd
    - main/summary.qmd
    - main/introduction.qmd
    - main/background.qmd
    - main/kNNTheory.qmd
    - main/mudra.qmd
    - main/fuse.qmd
    - main/conclusion.qmd
    - references.qmd
  appendices:
    - appendix/technicalProofs.qmd

bibliography: references.bib
csl: ieee-transactions-on-pattern-analysis-and-machine-intelligence.csl

format:
  html:
    include-in-header:
      - text: |
          <script>
            MathJax = {
              loader: {
                load: ["[tex]/boldsymbol"],
              },
              tex: {
                tags: "all",
                inlineMath: [["$", "$"], ["\\(", "\\)"]],
                displayMath: [["$$", "$$"], ["\\[", "\\]"]],
                processEscapes: true,
                processEnvironments: true,
                packages: {
                  "[+]": ["boldsymbol"],
                },
                macros: {symbf: ['\\boldsymbol{#1}', 1]}
              },
            };
            </script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js"></script>
      - mathCommands.html
    theme:
      - cosmo
      - brand
