project:
  type: book

filters:
  - acronyms

acronyms:
  loa_title: ""
  insert_loa: false
  keys:
    - shortname: MUDRA
      longname: Multivariate Functional Linear Discriminant Analysis
    - shortname: F3I
      longname: Fast Iterative Improvement for Imputation
    - shortname: FUSE
      longname: Fast Semi-Supervised Node Embedding via Structural and Label-Aware Optimization
    - shortname: MCAR
      longname: Missing Completely at Random
    - shortname: MAR
      longname: Missing At Random
    - shortname: MNAR
      longname: Missing Not at Random
    - shortname: kNN
      longname: K-Nearest Neighbours

book:
  title: "Imputation and Beyond: Missingness-Aware Learning for Downstream Tasks"
  author: "Rahul Bordoloi"
  date: "4/10/2026"
  chapters:
    - index.qmd
    # - mathCommands.qmd
    - preface/abstract.qmd
    - preface/zusammenfassung.qmd
    - preface/theses.qmd
    - preface/loa.qmd
    - main/summary.qmd
    - main/introduction.qmd
    - main/background.qmd
    - main/kNNTheory.qmd
    - main/mudra.qmd
    - main/fuse.qmd
    - main/conclusion.qmd
    - references.qmd
  appendices:
    - appendix/technicalProofs.qmd

bibliography: references.bib
csl: ieee-transactions-on-pattern-analysis-and-machine-intelligence.csl

format:
  pdf:
    documentclass: MastersDoctoralThesis
    classoption: 
      - openany
      - 11pt
      - english
      - singlespacing
      - headsepline
    title-page: false
    toc: false
    cite-method: biblatex
    biblatexoptions:
      - style=authoryear
      - backend=biber
    include-in-header: 
      - preamble.tex
      # - mathCommands.tex
    include-before-body: titlepage.tex
  html:
    include-in-header:
      - text: "<script>window.MathJax = {tex: {macros: {symbf: ['\\\\boldsymbol{#1}', 1]}}}</script>"
      - mathCommands.html
    theme:
      - cosmo
      - brand
  epub: default
