# State of the Art in Missingness-Aware Learning {#sec-background}

* Multivariate Imputation by Chained Equations and its variants
* Ensemble methods - HyperImpute, RF-GAP
* Modern deep learning-based / generative supervised imputation methods - GAIN, MIRACLE, ReMasker, etc.
* Imputation in time-series: LOCF, CSDI, DISK, etc.
* kNN imputation: History and controversies (IQ and the Wealth of Nations, 2005)
* (Morvan and Varoquaux, 2025) - why better imputation doesn't necessarily imply better downstream task performance.
* Models for joint imputation-downstream task: NeuMiss, GRAPE, etc. (Relate to [Chapter -@sec-knnTheory])
* Models that perform downstream tasks without imputation - FLDA (Relate to [Chapter -@sec-mudra])
* Models that perform imputation in more complex structures, eg. graphs (Relate to [Chapter -@sec-fuse])

## Iterative Imputation

One of the earliest major advancements in multivariate imputation was by @mice, called `MICE`. `MICE` is a general approach that starts off from a naive imputation, and then iteratively fits a univariate regression model on each feature to impute the missing feature values. It is computationally efficient, highly adaptable as it can be used with any regression model. It can also specify different regression models for each features, and this can be used for all types of tabular data, be it numeric, categorical, or mixed. Because of this flexibility and computational efficiency, `MICE` remains one of the most widely adopted imputation methods in the literature.

Another highly successful approach to imputation has been ensemble methods, such as `HyperImpute`[@hyperimpute] and `RF-GAP`[@rfgap]. `HyperImpute` attempts to make the iterative imputation process more flexible, by allowing a model search using `AutoML`[@automl] methods over multiple regression models for each feature. On the other hand, `RF-GAP` defines a novel proximity measure on an ensemble of binary recursive trees, and computes a proximity-based sum to impute missing values.

<!--Link to 1.1.2-->

## Generative Imputation

Another line of research views imputation as a generative process. The idea is to estimate the conditional distribution of the missing values given the observed ones, and sample from this distribution to impute missing values. Generative models usually sample from a simple, known distribution, like a multivariate normal distribution, and transform these samples to match the required conditional distribution. The mechanism of transformation and the assumed form of the conditional distribution separates these models.

One of the simplest methods to do this is to adapt a \acr{DLVM} to generate imputations for missing values. \acr{DLVM}s draw samples (known as the latent variable) from a simple known prior distribution, usually a Gaussian. They then attempt to approximate the posterior distribution of the observed values over this latent variable by fitting a parameterized family of distributions conditioned on it. This family is usually parameterized as a simple family (like a Gaussian), over a parameterized transformation of the latent variable, usually via a neural network. Sampling from this posterior is often either intractable or has an impractical convergence rate, so amortized variational inference is used to estimate another parameterized proposal distribution that is as close as possible to the posterior. These approaches have been explored in works like @miwae and @notmiwae, for different assumptions on the missingness mechanism.

Another early approach was to modify a \acr{GAN} to generate imputations for missing values. The missing values are initially imputed by draws from a simple distribution like a Gaussian, and then the generator network is used to transform these samples to match the required conditional distribution. An adversarial discriminator network is then trained to estimate the corresponding missingness mask, and the generator is again trained 

<!--Be careful not to mix up the research gaps and this chapter. This should only have the SotA-->
