# Error Guarantees for Nearest-Neighbor Imputation {#sec-knnTheory}


Despite the wide methodological diversity of modern approaches to imputation, most real-world settings still use simple imputation techniques like padding, central tendency measures, nearest-neighbor approaches or MICE[@methodsInPractice]. However, many of these machine learning approaches come without any guarantees on the quality of imputation, or often the only guarantees available are in the more straightforward \acr{MCAR} and \acr{MAR} settings. As shown in @exm-MNAR, in many biomedical settings like \acr{PROM} datasets, the missingness pattern actually follows the \acr{MNAR} mechanism.

Nearest-neighbor imputers[@knnImputer] are known to have good performance in practice and are relatively fast[@knnSurvey1; @knnSurvey2; @knnSurvey3]. However, this comes at the cost of a drop in performance for classification tasks in high-dimensional datasets[@knnPerfHighDim]. This limitation does not necessarily extend to other downstream tasks. In my experiments on the outlier detection task, where additional irrelevant features containing no informative signal were introduced solely to increase the dimensionality, I found that \acr{kNN}-based methods remained robust to the presence of such irrelevant features[@msde].

In this chapter, I will first propose a general description of iterative \acr{kNN}-based approaches for imputation. I will then describe a general proof strategy for deriving theoretical bounds for imputation quality on this meta-algorithm. After that, I will describe \acr{F3I}, a novel modification of the classical \acr{kNN} imputation algorithm which can automatically be tuned for downstream tasks, and can handle mixed-type variables. I will also use the general proof strategy to derive theoretical bounds for this method. Finally, I will empirically show that \acr{kNN}-based approaches are competitive performance-wise to the \acr{SotA}, while being much faster.

<!--Throughout this chapter, we will use $\triangle_K\deff \{\symbf{p} \in [0,1]^K \mid \sum_{k \leq K} p_k = 1 \}$ as the simplex of dimension K.-->

## Meta-algorithm for \acr{kNN}

::: {#algo-metaKNN}

```pseudocode
#| html-indent-size: "1.2em"
#| html-comment-delimiter: "#"
#| html-line-number: true
#| html-line-number-punc: ":"
#| html-no-end: false
#| pdf-line-number: true
#| pdf-comment-delimiter: "\#"
#| pdf-right-comment: true
#| label: algo-metaKNN

\begin{algorithm}
\caption{General weighted nearest-neighbor (NN) imputation meta-algorithm.}
\begin{algorithmic}
  \State {\bfseries Input:} Data $X \in (\mathbb{R}\cup\{\texttt{N/A}\})^{N \times F}$
  \State {\bfseries Parameters:} Number of neighbors $K \geq 2$, Weight update function $f_{w} : \triangle_K \times \mathbb{R}^{N \times F} \rightarrow \triangle_K$, Stopping criterion $s : \triangle_K \times \mathbb{R}^{N \times F} \rightarrow \{\text{True},\text{False}\}$, Nearest-neighbor search algorithm $\mathcal{A}$
  \State {\bfseries Output:} Imputed data $\widehat{X} \in \mathbb{R}^{N \times F}$
  \State Initialize $\mathcal{A}$ with $Z = \{\symbf{x}_1,\symbf{x}_2, \dots, \symbf{x}_N\}$ and $\widehat{X} \gets X$\Comment{Initialize NN search}
  \State $\symbf{\alpha} \gets 1/K,\;\textbf{1}_K \triangleq \{1/K, 1/K, \dots, 1/K\}$\Comment{Initialize the K neighbor-dependent weights}
  \State $t \gets 0$
  \State {\bfseries return} $\widehat{X}$
  \While{{\bfseries not} $s(\symbf{\alpha}, \widehat{X}, t)$} 
      \State  $\symbf{\alpha} \gets f_{w}(\symbf{\alpha}, \widehat{X})$\Comment{Update the K neighbor-dependent weights}
      \For{$i \leq N$ and $f \leq F$}
          \State $(\symbf{z}^{i,f})_1, (\symbf{z}^{i,f})_2, \dots, (\symbf{z}^{i,f})_K \gets \mathcal{A}(\widehat{\symbf{x}}_i)$
      \EndFor
      \State $t \gets t +1 $
  \EndWhile
\end{algorithmic}
\end{algorithm}
```
:::

@algo-metaKNN defines the broad structure of an iterative convex-weighted nearest-neighbor approach to imputation.
$\alpha, \beta$
